apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rockcairn
  namespace: apenner
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rockcairn
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: master
      url: https://github.com/rockcairn/tanzu-java-rc-demo.git